[project]

name = "fmmax"
version = "v0.11.0"
description = "Fourier modal method with JAX"
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
license-files = ["LICENSE"]

keywords = ["fmm", "rcwa", "jax", "optics"] 

authors = [
  {name = "Martin Schubert", email = "mfschubert@gmail.com" },
  {name = "Alec Hammond", email = "alec.m.hammond@gmail.com" },
]

maintainers = [
  {name = "matt8s"},
]

dependencies = [
  "jax >= 0.4.38, <= 0.11.2",
  "jaxlib >= 0.4.38, <= 0.11.2",
  "numpy",
]
[project.urls]
Repository = "https://github.com/matt8s/fmmax"
Issues = "https://github.com/matt8s/fmmax/issues"
Documentation = "https://facebookresearch.github.io/fmmax/"
Upstream = "https://github.com/facebookresearch/fmmax"

[project.optional-dependencies]
cuda12 = [
  "jax[cuda12] >= 0.4.38, <= 0.11.2",
]
cuda13 = [
  "jax[cuda13] >= 0.10.2, <= 0.11.2",
]
jeig = [
  "jeig",
]
tests = [
  "grcwa",
  "parameterized",
  "pytest",
  "pytest-subtests",
]
examples = [
  "matplotlib",
  "scikit-image",
  "scipy",
]
docs = [
  "docstring-parser",
  "nbconvert",
  "nbformat",
]
dev = [
  "black",
  "bump-my-version",
  "darglint",
  "fmmax[docs, examples, tests]",
  "isort",
  "mypy",
]

[build-system]
requires = ["setuptools>=77.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
target-version = ["py310"]

[tool.setuptools.package-data]
"fmmax" = ["py.typed"]

[tool.pytest.ini_options]
addopts = ["--import-mode=importlib"]  # Allow tests with same name in different dirs.
pythonpath = ["src"]

[[tool.mypy.overrides]]
module = ["jeig"]
ignore_missing_imports = true
